apiVersion: v2
appVersion: 2.11.2
dependencies:
- name: testkube-operator
  repository: file://../testkube-operator
  version: 2.x.x-x
- condition: mongodb.enabled
  name: mongodb
  repository: oci://us-east1-docker.pkg.dev/testkube-cloud-372110/testkube
  version: 8.3.1-0
- condition: postgresql.enabled
  name: postgresql
  repository: oci://us-east1-docker.pkg.dev/testkube-cloud-372110/testkube
  version: 18.3-0
- condition: cloudnative-pg.enabled
  name: cloudnative-pg
  repository: https://cloudnative-pg.github.io/charts
  version: 0.28.3
- alias: postgresqlOperatorCluster
  condition: postgresqlOperatorCluster.enabled
  name: cluster
  repository: https://cloudnative-pg.github.io/charts
  version: 0.7.0
- condition: testkube-api.nats.enabled
  name: nats
  repository: file://./charts/nats
  version: 1.2.6-4
- name: testkube-api
  repository: file://../testkube-api
  version: 2.x.x-x
- name: global
  repository: file://../global
  version: 0.x.x-x
description: Testkube is an open-source platform that simplifies the deployment and
  management of automated testing infrastructure.
name: testkube
type: application
version: 2.11.2
