apiVersion: v1
kind: Namespace
metadata:
  name: strimzi-kafka
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: strimzi-kafka
    istio.io/dataplane-mode: none
