# Shared Strimzi operator config

# Keep operator scoped to this namespace only.
watchAnyNamespace: false
watchNamespaces:
  - strimzi-kafka

# Use the private third-party ACR pull-through cache.
defaultImageRegistry: quay.io
defaultImageRepository: strimzi
