{
 "title": "Alloy / Cluster Overview",
 "tags": [ "alloy-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(alloy_component_controller_running_components, cluster)\n"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\"}, namespace)\n"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(alloy_component_controller_running_components{cluster=~\"$cluster\", namespace=~\"$namespace\"}, job)\n"
    }
   },
   { "name": "filters" },
   {
    "name": "groupby",
    "label": "Group by",
    "query": "instance,state,job,namespace,cluster,pod"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(cluster_node_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node table",
   "type": "table",
   "description": "Nodes info.\n",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "cluster_node_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Convergence state",
   "type": "stat",
   "description": "Whether the cluster state has converged.\n\nIt is normal for the cluster state to be diverged briefly as gossip events propagate. It is not normal for the cluster state to be diverged for a long period of time.\n\nThis will show one of the following:\n\n* Converged: Nodes are aware of all other nodes, with the correct states.\n* Not converged: A subset of nodes aren't aware of their peers, or don't have an updated view of peer states.\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "suffix:nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp((\n  sum(stddev by (state) (cluster_node_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}) != 0) or\n  (sum(abs(sum without (state) (cluster_node_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})) - scalar(count(cluster_node_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})) != 0))\n  ),\n  1, 1\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Convergence state timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "ceil(clamp((\n  sum(stddev by (state) (cluster_node_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})) or\n  (sum(abs(sum without (state) (cluster_node_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})) - scalar(count(cluster_node_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}))))\n  ),\n  0, 1\n))\n",
     "legendFormat": "Converged"
    }
   ]
  },
  {
   "title": "Number of peers seen by each instance",
   "type": "timeseries",
   "description": "The number of cluster peers seen by each instance.\n\nWhen cluster is converged, every peer should see all the other instances. When we have a split brain or one\npeer not joining the cluster, we will see two or more groups of instances that report different peer numbers\nfor an extended period of time and not converging.\n\nThis graph helps to identify which instances may be in a split brain state.\n\nThe minimum cluster size shows the value of the --cluster.wait-for-size flag, which specifies the minimum \nnumber of instances required before cluster-enabled components begin processing traffic.\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "peers" } },
   "targets": [
    {
     "expr": "sum by(${groupby}) (cluster_node_peers{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(cluster_minimum_size{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"})\n",
     "legendFormat": "Minimum cluster size"
    }
   ]
  }
 ]
}