apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: dragonfly-v1.36.0
    version: v1.36.0
    releaseName: dragonfly
    namespace: dragonfly
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
