apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system

resources:
  - namespace.yaml
  - mtls.yaml
  - peer-auth-kube-apiserver.yaml

# patches:
# - target:
#     kind: ValidatingWebhookConfiguration
#     name: istiod-default-validator
#   patch: |-
#     - op: replace
#       path: /webhooks/0/failurePolicy
#       value: Fail

