apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: istio
    allow-shared-gateway-int-access: "true"
    istio.io/dataplane-mode: ambient
    istio.io/use-waypoint: shared-waypoint
    istio.io/use-waypoint-namespace: gateway-api
    allow-shared-waypoint-access: "true"

