{{- if .Values.backendScheduler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.resourceName" (dict "ctx" . "component" "backend-scheduler") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "backend-scheduler") | nindent 4 }}
  {{- with .Values.backendScheduler.service.annotations }}
  annotations:
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http-metrics
      port: 3200
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: 9095
  {{- if .Values.tempo.useHeadlessGoverningService }}
  publishNotReadyAddresses: true
  {{- end }}
  selector:
    {{- include "tempo.selectorLabels" (dict "ctx" . "component" "backend-scheduler") | nindent 4 }}
  ipFamilies: {{ .Values.tempo.service.ipFamilies }}
  ipFamilyPolicy: {{ .Values.tempo.service.ipFamilyPolicy }}
{{- end }}
