apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../../charts/trivy-operator-0.32.0/crds

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

configMapGenerator:
  - name: external-config
    namespace: trivy-operator
    options:
      disableNameSuffixHash: true
    envs:
      - config.properties

replacements:
  # Replace workload identity client_id in ServiceAccount
  - source:
      kind: ConfigMap
      name: external-config
      fieldPath: data.client_id
    targets:
      - select:
          kind: ServiceAccount
          name: trivy-operator
        fieldPaths:
          - metadata.annotations.[azure.workload.identity/client-id]

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: trivy-operator-0.32.0
    version: 0.32.0
    releaseName: trivy-operator
    namespace: trivy-operator
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
