apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: prometheus-blackbox-exporter-11.6.1
    version: 11.6.1
    releaseName: blackbox-exporter
    namespace: blackbox-exporter
    additionalValuesFiles:
      - values-additional.yaml