apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - networkpolicy.yml
  - requestauthentication.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: gateway-api-1.6.1
    version: 1.6.1
    releaseName: gateway-api
    namespace: gateway-api
    includeCRDs: true
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml

