apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
    argocd.argoproj.io/sync-wave: '2'
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: kv-pin-aks-devm-int-uks
  target:
    name: oauth2-proxy-credentials
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oauth2-client-id
        metadataPolicy: None
    - secretKey: client-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oauth2-client-secret
        metadataPolicy: None
    - secretKey: cookie-secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oauth2-cookie-secret
        metadataPolicy: None
