apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - externalsecret.yaml
  - secretstore.yaml

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: oauth2-proxy-10.3.0
    version: 10.3.0
    releaseName: platform-auth
    namespace: platform-auth
    additionalValuesFiles:
      - values-additional.yaml
