apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
    argocd.argoproj.io/sync-wave: '-2'
spec:
  provider:
    gcpsm:
      projectID: gcp-project-id
      serviceAccountRef:
        name: oauth2-proxy
