apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kv-pin-aks-devm-int-uks
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://kv-pin-aks-devm-int-uks.vault.azure.net/
      serviceAccountRef:
        name: oauth2-proxy
