{{- if .Values.liveStore.enabled }}
{{- $zonesMap := include "live-store.zoneAwareReplicationMap" (dict "ctx" $) | fromYaml -}}
{{- $zoneAware := .Values.liveStore.zoneAwareReplication -}}
{{- $prepareDownscale := $zoneAware.prepareDownscale | default dict -}}
{{- range $zoneName, $rolloutZone := $zonesMap -}}
{{- with $ -}}
{{- $dict := dict "ctx" . "component" "live-store" "memberlist" true "rolloutZoneName" $zoneName -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
    {{- with .Values.liveStore.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if $zoneName }}
    {{- if $zoneAware.noDownscale }}
    grafana.com/no-downscale: "true"
    {{- else if $prepareDownscale.enabled }}
    grafana.com/prepare-downscale: "true"
    {{- end }}
    {{- end }}
  {{- $annotations := mergeOverwrite (deepCopy (.Values.liveStore.annotations | default dict)) ($rolloutZone.annotations | default dict) }}
  {{- if $zoneName }}
  {{- if not (kindIs "invalid" $zoneAware.maxUnavailable) }}
  {{- $_ := set $annotations "rollout-max-unavailable" ($zoneAware.maxUnavailable | toString) }}
  {{- end }}
  {{- if and $prepareDownscale.enabled (not $zoneAware.noDownscale) }}
  {{- $_ := set $annotations "grafana.com/prepare-downscale-http-path" $prepareDownscale.httpPath }}
  {{- $_ := set $annotations "grafana.com/prepare-downscale-http-port" (.Values.server.httpListenPort | toString) }}
  {{- with $prepareDownscale.minTimeBetweenZonesDownscale }}
  {{- $_ := set $annotations "grafana.com/min-time-between-zones-downscale" (. | toString) }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $rolloutZone.replicas }}
  revisionHistoryLimit: {{ .Values.tempo.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
  {{- if $zoneName }}
  serviceName: {{ include "tempo.resourceName" (dict "ctx" . "component" "live-store") }}
  {{- else }}
  serviceName: {{ include "tempo.governingServiceName" (dict "ctx" $ "component" "live-store") }}
  {{- end }}
  podManagementPolicy: Parallel
  updateStrategy:
    {{- if $zoneName }}
    type: OnDelete
    {{- else }}
    {{- toYaml .Values.liveStore.statefulStrategy | nindent 4 }}
    {{- end }}
  template:
    {{- $podArgs := list }}
    {{- if $zoneName }}
    {{- $podArgs = list (printf "-live-store.instance-availability-zone=%s" $zoneName) }}
    {{- end }}
    {{- include "tempo.podTemplate" (dict "ctx" $ "component" .Values.liveStore "target" "live-store" "rolloutZoneName" $zoneName "rolloutZone" $rolloutZone "args" $podArgs) | nindent 4 }}
{{ end }}
{{- end }}
{{- end }}
