{{- if and .Values.backendScheduler.enabled .Values.backendWorker.autoscaling.enabled .Values.backendWorker.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tempo.resourceName" (dict "ctx" . "component" "backend-worker") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" . "component" "backend-worker") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "tempo.resourceName" (dict "ctx" . "component" "backend-worker") }}
  minReplicas: {{ .Values.backendWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backendWorker.autoscaling.maxReplicas }}
  {{- with .Values.backendWorker.autoscaling.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  metrics:
  {{- with .Values.backendWorker.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.backendWorker.autoscaling.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
{{- end }}
