{{- if and .Values.backendScheduler.enabled .Values.backendWorker.autoscaling.enabled .Values.backendWorker.autoscaling.keda.enabled }}
{{- include "tempo.lib.keda" (dict "ctx" $ "component" .Values.backendWorker "target" "backend-worker") }}
{{- end }}
