{{- if and (.Values.metricsGenerator.enabled) (eq .Values.metricsGenerator.kind "StatefulSet") }}
{{ $dict := dict "ctx" . "component" "metrics-generator" "memberlist" true }}
{{- $storageClass := .Values.metricsGenerator.persistence.storageClass | default .Values.global.storageClass }}
{{- if eq $storageClass "-" }}{{- $storageClass = "" }}{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "tempo.labels" $dict | nindent 4 }}
  {{- with .Values.metricsGenerator.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minReadySeconds: {{ .Values.metricsGenerator.minReadySeconds }}
  replicas: {{ .Values.metricsGenerator.replicas }}
  podManagementPolicy: Parallel
  updateStrategy:
    rollingUpdate:
      partition: 0
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
  serviceName: {{ include "tempo.governingServiceName" (dict "ctx" $ "component" "metrics-generator") }}
  template:
    {{- include "tempo.podTemplate" (dict
        "ctx" .
        "component" .Values.metricsGenerator
        "target" "metrics-generator"
        "persistence" .Values.metricsGenerator.persistence
        "dataVolumeName" "wal"
        "dataEmptyDir" .Values.metricsGenerator.walEmptyDir
        "ports" .Values.metricsGenerator.ports) | nindent 4 }}
  {{- if .Values.metricsGenerator.persistence.enabled }}
  {{- if .Values.metricsGenerator.persistentVolumeClaimRetentionPolicy.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.metricsGenerator.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.metricsGenerator.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        {{- with .Values.metricsGenerator.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.metricsGenerator.persistence.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: wal
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ if $storageClass }}{{ $storageClass }}{{ else }}{{- "" }}{{ end }}
        resources:
          requests:
            storage: {{ .Values.metricsGenerator.persistence.size | quote }}
  {{- end }}
{{- end }}
