{{- $ingress := .Values.networkPolicy.ingress | default dict }}

{{- if $ingress.policyFromCatalogue }}

{{- range $policyName := $ingress.policyFromCatalogue }}

{{- $policy := index $.Values.ingressPolicyCatalogue $policyName }}

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ $policyName }}
  namespace: {{ $.Release.Namespace }}


spec:
{{- if and $policy.targetService (ne $policy.scope "namespace") }}
  targetRefs:
  - kind: Service
    group: ""
    name: {{ $policy.targetService }}
{{- end }}

  action: {{ $policy.action | default "ALLOW" }}

  rules:

{{- range $rule := $policy.rules }}

  -

{{- if $rule.from }}
    from:
    - source:

{{- if $rule.from.principals }}
        principals:
{{- range $rule.from.principals }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- if $rule.from.namespaces }}
        namespaces:
{{- range $rule.from.namespaces }}
        {{- if eq . "." }}
        - "{{ $.Release.Namespace }}"
        {{- else }}
        - {{ . | quote }}
        {{- end }}
{{- end }}
{{- end }}

{{- if $rule.from.ipBlocks }}
        ipBlocks:
{{- range $rule.from.ipBlocks }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- if $rule.from.remoteIpBlocks }}
        remoteIpBlocks:
{{- range $rule.from.remoteIpBlocks }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- if $rule.from.requestPrincipals }}
        requestPrincipals:
{{- range $rule.from.requestPrincipals }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- end }}

{{- if $rule.to }}
    to:
    - operation:

{{- if $rule.to.hosts }}
        hosts:
{{- range $rule.to.hosts }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- if $rule.to.methods }}
        methods:
{{- range $rule.to.methods }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- if $rule.to.paths }}
        paths:
{{- range $rule.to.paths }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- if $rule.to.ports }}
        ports:
{{- range $rule.to.ports }}
        - {{ . | quote }}
{{- end }}
{{- end }}

{{- end }}

{{- if $rule.when }}
    when:
{{- range $condition := $rule.when }}
    - key: {{ $condition.key | quote }}
      values:
{{- range $condition.values }}
      - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}

{{- end }}
{{- end }}