{{- $selectedPolicies := .Values.networkPolicy.egress.policyFromCatalogue | default list }}

{{- range $policyName := $selectedPolicies }}

{{- $cfg := index $.Values.egressCatalogue $policyName }}

{{- if and $cfg (or (not $cfg.location) (eq $cfg.location "MESH_EXTERNAL")) }}

{{- $resolution := default "" $cfg.resolution }}

{{- if eq $resolution "" }}
  {{- range $cfg.hosts }}
    {{- if contains "*" . }}
      {{- $resolution = "NONE" }}
    {{- end }}
  {{- end }}

  {{- if eq $resolution "" }}
    {{- $resolution = "DNS" }}
  {{- end }}
{{- end }}

---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ $policyName }}
  namespace: {{ $.Release.Namespace }}

spec:
  hosts:
{{- range $cfg.hosts }}
    - {{ . | quote }}
{{- end }}

  exportTo:
    - "."

  location: MESH_EXTERNAL
  resolution: {{ $resolution }}

  ports:
    - number: {{ $cfg.port }}
      name: {{ $cfg.portName }}
      protocol: {{ $cfg.protocol }}

{{- end }}
{{- end }}