apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argo-cd
data:
  resource.exclusions: |
    - apiGroups:
      - ""
      kinds:
      - ConfigMap
      clusters:
      - "*"
      namespaces:
      - kube-system
      name: "*-external-config"
