apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secret-store
spec:
  provider:
    gcpsm:
      projectID: "project-c487c7e3-8780-4424-9ad"
      # Using GKE Workload Identity. No need for a Secret containing service account keys!
      auth:
        workloadIdentity:
          clusterLocation: "asia-south1-a"
          clusterName: "enterprise-gke-cluster"
          clusterProjectID: "project-c487c7e3-8780-4424-9ad"
          serviceAccountRef:
            name: "external-secrets-sa"
            namespace: "external-secrets"
