apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: external-secrets-1.2.0
    releaseName: external-secrets
    version: 1.2.0
    namespace: external-secrets
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
