image:
  repository: ghcr.io/external-secrets/external-secrets

# Resources: req==lim (VPA upper: ~128Mi for all components)
resources:
  requests:
    cpu: 15m
    memory: 100Mi
  limits:
    cpu: 15m
    memory: 100Mi

nodeSelector:
  kubernetes.io/os: linux

certController:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi
  nodeSelector:
    kubernetes.io/os: linux

webhook:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi
  nodeSelector:
    kubernetes.io/os: linux

serviceAccount:
  name: external-secrets-sa
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@project-c487c7e3-8780-4424-9ad.iam.gserviceaccount.com
