image:
  repository: docker.io/external-secrets/external-secrets

# Resources: req==lim (VPA upper: ~128Mi for all components)
resources:
  requests:
    cpu: 15m
    memory: 100Mi
  limits:
    cpu: 15m
    memory: 100Mi

nodeSelector:
  karpenter.sh/capacity-type: on-demand

certController:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi
  nodeSelector:
    karpenter.sh/capacity-type: on-demand

webhook:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi
  nodeSelector:
    karpenter.sh/capacity-type: on-demand

podLabels:
  azure.workload.identity/use: "true"

serviceAccount:
  name: external-secrets
  annotations:
    azure.workload.identity/client-id: 7539e514-9662-453f-bf3c-d41d421520d0
