apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-config-file
  namespace: external-dns
data:
  azure.json: |
    {
      "tenantId": "a47336de-50a0-418e-a3a6-0d36f185f6d4",
      "subscriptionId": "3541944e-fe2e-48d6-9d8d-ee21066d0d19",
      "resourceGroup": "rg-pin-aksshared-devm-int-uks-001",
      "useWorkloadIdentityExtension": true
    }
