apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap-azure-config.yaml

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: external-dns-1.19.0
    version: 1.19.0
    releaseName: external-dns-public
    namespace: external-dns
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional-public.yaml
  - name: external-dns-1.19.0
    version: 1.19.0
    releaseName: external-dns-private
    namespace: external-dns
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional-private.yaml
