fullnameOverride: external-dns-public

resources:
  requests:
    cpu: 15m
    memory: 100Mi
  limits:
    cpu: 15m
    memory: 100Mi

nodeSelector: {}

serviceAccount:
  name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: external-dns@prj-c-gke-8fbd.iam.gserviceaccount.com

domainFilters:
  - jksoam.in

provider:
  name: google
  google:
    project: prj-c-gke-8fbd

sources:
  - service
  - ingress
