apiVersion: v1
kind: Namespace
metadata:
  name: mimir
  labels:
    app.kubernetes.io/name: mimir
    # Enable Istio ambient mode for mTLS and traffic management
    istio.io/dataplane-mode: ambient
