apiVersion: v2
name: gateway-api
description: A Helm chart for Gateway API configuration
type: application
version: 1.6.1
appVersion: "v1.6.1" # Gateway API version
maintainers:
  - name: PPUK DevOps team