apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: karpenter-crd-1.14.0
    version: 1.14.0
    releaseName: karpenter
    namespace: karpenter
  - name: karpenter-1.14.0
    version: 1.14.0
    releaseName: karpenter
    namespace: karpenter
    additionalValuesFiles:
      - values-additional.yaml
