apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - clusterissuer-k01.devm.corp.pinpetuk.net.yaml
  - clusterissuer-k01.devm.pinpetuk.net.yaml

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: jetstack-cert-manager-v1.18.1
    version: v1.18.1
    releaseName: cert-manager
    namespace: cert-manager
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
