crds:
  enabled: true

resources:
  requests:
    cpu: 15m
    memory: 100Mi
  limits:
    cpu: 15m
    memory: 100Mi

nodeSelector: {}

cainjector:
  enabled: true
  resources:
    requests:
      cpu: 15m
      memory: 139Mi
    limits:
      cpu: 15m
      memory: 139Mi
  nodeSelector: {}

webhook:
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi
  nodeSelector: {}

startupapicheck:
  nodeSelector: {}

serviceAccount:
  name: cert-manager
  annotations:
    iam.gke.io/gcp-service-account: cert-manager@prj-c-gke-8fbd.iam.gserviceaccount.com

extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
