apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: generic-linux
  annotations:
    kubernetes.io/description: "linux NodePool for stable workloads"
spec:
  weight: 10
  template:
    spec:
      requirements:
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.azure.com/mode
          operator: In
          values: ["user"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: 
          operator: In
          values: ["Das_v5", "Eas_v5"]
        - key: 
          operator: Gte
          values: ["2"]
        - key: 
          operator: Lte
          values: ["16"]
        - key: 
          operator: Gte
          values: ["8192"]
        - key: 
          operator: Lte
          values: ["65536"]
        - key: 
          operator: In
          values: ["true"]
        - key: 
          operator: In
          values: ["true"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["uksouth-1", "uksouth-2", "uksouth-3"]
      nodeClassRef:
        group: 
        kind: AKSNodeClass
        name: default
  limits:
    cpu: "48"
    memory: 192Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 10m
    budgets:
      - nodes: "10%"
