apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: prometheus-node-exporter-4.56.1
    releaseName: node-exporter
    namespace: node-exporter
    additionalValuesFiles:
      - values-additional.yaml
