apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - httproute.yaml

# SSA avoids client-side last-applied annotation bloat on large CRDs
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: chaos-mesh-2.8.2
    version: 2.8.2
    releaseName: chaos-mesh
    namespace: chaos-mesh
    includeCRDs: true
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
