# Keep controller on standard nodes; daemonset still runs on all Linux nodes.
controllerManager:
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi

dnsServer:
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi

dashboard:
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 15m
      memory: 100Mi
    limits:
      cpu: 15m
      memory: 100Mi

chaosDaemon:
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 23m
      memory: 100Mi
    limits:
      cpu: 23m
      memory: 100Mi
