apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    gcpsm:
      projectID: gcp-project-id
      serviceAccountRef:
        name: grafana-sa

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: grafana-sa
#   namespace: grafana-shared
#   annotations:
#     azure.workload.identity/client-id: placeholder
#     kubernetes.io/enforce-mountable-secrets: "true"
#     argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
#     argocd.argoproj.io/sync-wave: "-2"

# secrets:
#   - name: grafana-shared-user-secret

