# ACR third-party images
opencost:
  exporter:
    image:
      registry: docker.io
      repository: opencost/opencost
  ui:
    image:
      registry: docker.io
      repository: opencost/opencost-ui
