apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-shared
  namespace: cnpg-shared
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: 2m
      scrapeTimeout: 30s
