apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# SSA required for CNPG Cluster status drift
commonAnnotations:
  argocd.argoproj.io/sync-options: ServerSideApply=true

resources:
  - ../../base
  - cnpg-user-grafana-shared.yaml
  - cnpg-user-magnolia-author-shared.yaml
  - es-postgtresadmin.yaml
  - objectstore.yaml
  - postgresql-cluster.yaml
  - scheduled-backup.yaml
  - sa-cnpg-shared.yaml
  - ss-kv-pin-mgtcluster-mgt.yaml

# Generate ConfigMap from properties file
configMapGenerator:
  - name: cnpg-shared-external-config
    namespace: cnpg-shared
    options:
      disableNameSuffixHash: true
    envs:
      - config.properties


# Replace placeholder values in grafana.yaml
replacements:
  - source:
      kind: ConfigMap
      name: cnpg-shared-external-config
      fieldPath: data.client_id
    targets:
      - select:
          kind: ServiceAccount
          name: cnpg-shared
        fieldPaths:
          - metadata.annotations.[azure.workload.identity/client-id]
          
# Override base StorageClass with CSI provisioner for mgt-k01
patches:
  - path: postgresql-premiumv2-storageclass.yaml
