apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresql-premiumv2
# mgt-k01 uses CSI driver with explicit IOPS/throughput settings
provisioner: pd.csi.storage.gke.io
parameters:
  $patch: replace
  skuName: PremiumV2_LRS
  DiskIOPSReadWrite: "3000"
  DiskMBpsReadWrite: "125"
  cachingMode: None
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
