apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    gcpsm:
      projectID: project-c487c7e3-8780-4424-9ad
