apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: grafana-operator-5.22.0
    version: 5.22.0
    releaseName: grafana-operator
    namespace: grafana-operator
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
