apiVersion: v1
kind: Namespace
metadata:
  name: dragonfly
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: dragonfly
    # Istio ambient mode - use shared waypoint for L7 features
    istio.io/use-waypoint: shared-waypoint
    istio.io/use-waypoint-namespace: gateway-api
    allow-shared-waypoint-access: "true"
