# Environment-specific overrides for devm-k01
auth:
  enabled: true
  hostname: kiali.jksoam.in
  requiredRoles:
    - "kiali.access"

login_token:
  signing_key: "tTkavZhMVeFgrgJ6P9Wla0NPwxIBw5T9"

# Resources: req==lim (VPA upper: ~128Mi)
deployment:
  node_selector:
    kubernetes.io/os: linux
  tolerations: []
  resources:
    requests:
      cpu: 23m
      memory: 121Mi
    limits:
      cpu: 23m
      memory: 122Mi
