# Shared ExternalDNS configuration

# ACR third-party image
image:
  repository: docker.io/external-dns/external-dns

replicaCount: 2

policy: sync

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 128Mi

# Run as non-root
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
