apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-shared
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: cnpg-shared
    istio.io/use-waypoint: shared-waypoint
    istio.io/use-waypoint-namespace: gateway-api
    allow-shared-waypoint-access: "true"
