# Shared External Secrets configuration

replicaCount: 2

certController:
  replicaCount: 2

webhook:
  replicaCount: 2

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    memory: 128Mi

certController:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
