client_id=6159ba8a-6c94-4c3e-aeea-ae558da28a37
alertmanager_container_name=mimir-alertmanager
alertmanager_teams_webhook_secret=mimir-alertmanager-teams-webhook
blocks_container_name=mimir-blocks
ruler_container_name=mimir-ruler
storage_account_name=stpinaksshareddevmintuks