# Capacity placement for every chart-managed Mimir PodSpec in devm.

alertmanager:
  nodeSelector:
    kubernetes.io/os: linux

compactor:
  nodeSelector:
    kubernetes.io/os: linux

distributor:
  nodeSelector:
    kubernetes.io/os: linux
  affinity: null

gateway:
  nodeSelector:
    kubernetes.io/os: linux

ingester:
  nodeSelector:
    kubernetes.io/os: linux

overrides_exporter:
  nodeSelector:
    kubernetes.io/os: linux

querier:
  nodeSelector:
    kubernetes.io/os: linux
  affinity: null

query_frontend:
  nodeSelector:
    kubernetes.io/os: linux
  affinity: null

query_scheduler:
  nodeSelector:
    kubernetes.io/os: linux

rollout_operator:
  nodeSelector:
    kubernetes.io/os: linux

ruler:
  nodeSelector:
    kubernetes.io/os: linux

store_gateway:
  zoneAwareReplication:
    zones:
      - name: zone-a
        nodeSelector:
          kubernetes.io/os: linux
        extraAffinity: {}
        storageClass: null
        noDownscale: false
        downscaleLeader: null
        prepareDownscale: true
      - name: zone-b
        nodeSelector:
          kubernetes.io/os: linux
        extraAffinity: {}
        storageClass: null
        noDownscale: false
        downscaleLeader: null
        prepareDownscale: true
      - name: zone-c
        nodeSelector:
          kubernetes.io/os: linux
        extraAffinity: {}
        storageClass: null
        noDownscale: false
        downscaleLeader: null
        prepareDownscale: true
