apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: istio-cni-1.29.1
    version: 1.29.1
    releaseName: istio-cni
    namespace: istio-system
    includeCRDs: true
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
