profile: ambient

resources:
  requests:
    cpu: 15m
    memory: 100Mi
  limits:
    cpu: 15m
    memory: 100Mi

tolerations:
  - effect: NoSchedule
    key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: linux
