apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: reloader-2.2.3
    version: 2.2.3
    releaseName: reloader
    namespace: reloader
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml