apiVersion: v1
kind: Namespace
metadata:
  name: kargo
  labels:
    app.kubernetes.io/name: kargo
    allow-shared-gateway-int-access: "true"
#    istio.io/dataplane-mode: ambient 
#    istio.io/use-waypoint: shared-waypoint
#    istio.io/use-waypoint-namespace: gateway-api
#    allow-shared-waypoint-access: "true"          # Label selector to allow waypoint access (service to service)