# Environment-specific overrides for devm-k01
image:
  repository: docker.io/skyhook-io/radar

auth:
  enabled: true
  hostname: radar.k01.devm.corp.pinpetuk.net
  requiredRoles:
    - "radar.access"
