{{- if .Values.blockBuilder.enabled }}
{{- if and (gt (int .Values.blockBuilder.replicas) 1) .Values.blockBuilder.podDisruptionBudget.enabled }}
{{ $dict := dict "ctx" . "component" "block-builder" "memberlist" true }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.resourceName" $dict }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
  maxUnavailable: {{ .Values.blockBuilder.maxUnavailable }}
  {{- with .Values.blockBuilder.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
