{{- if .Values.blockBuilder.enabled }}
{{- $dict := dict "ctx" . "component" "block-builder" "memberlist" true -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
    {{- with .Values.blockBuilder.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.blockBuilder.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.blockBuilder.replicas }}
  revisionHistoryLimit: {{ .Values.tempo.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
  serviceName: {{ include "tempo.governingServiceName" (dict "ctx" $ "component" "block-builder") }}
  podManagementPolicy: Parallel
  updateStrategy:
    {{- toYaml .Values.blockBuilder.statefulStrategy | nindent 4 }}
  template:
    {{- include "tempo.podTemplate" (dict "ctx" $ "component" .Values.blockBuilder "target" "block-builder") | nindent 4 }}
{{- end }}
