apiVersion: v2
name: troubleshooting-pod
description: Helm chart for an on-demand troubleshooting pod deployment
type: application
version: 0.1.0
appVersion: "v0.15"
maintainers:
  - name: PPUK DevOps team
