client_id=16bebcac-8e7e-480b-a568-67c6cbc8c092
alertmanager_container_name=tempo-alertmanager
alertmanager_teams_webhook_secret=tempo-alertmanager-teams-webhook
blocks_container_name=tempo-blocks
ruler_container_name=tempo-ruler
storage_account_name=stpinaksshareddevmintuks
traces_container_name=tempo-traces