apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - gcs-config.yaml

helmGlobals:
  chartHome: ../../../../charts

helmCharts:
  - name: tempo-distributed-3.5.1
    includeCRDs: true
    version: 3.5.1
    releaseName: tempo
    namespace: tempo
    additionalValuesFiles:
      - ../../base/values-common.yaml
      - values-additional.yaml
