apiVersion: v2
appVersion: 3.0.3
dependencies:
- alias: grafana-agent-operator
  condition: metaMonitoring.grafanaAgent.installOperator
  name: grafana-agent-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.5.2
- alias: rollout_operator
  condition: rollout_operator.enabled
  name: rollout-operator
  repository: https://grafana.github.io/helm-charts
  version: 0.51.1
description: Grafana Tempo in MicroService mode
home: https://grafana.com/docs/tempo/latest/
icon: https://raw.githubusercontent.com/grafana/tempo/main/cmd/tempo/app/static/tempo-icon.png
kubeVersion: ^1.25.0-0
maintainers:
- email: Ilia.lazebnik@gmail.com
  name: Ilia Lazebnik
  url: https://github.com/DrFaust92
- email: sheikhabubaker761@gmail.com
  name: Mohammad Abubaker
  url: https://github.com/Sheikh-Abubaker
- email: quentin.bisson@gmail.com
  name: Quentin Bisson
  url: https://github.com/QuentinBisson
name: tempo-distributed
sources:
- https://github.com/grafana/tempo
type: application
version: 3.5.1
