apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ARM64 NodePools (preferred for cost savings)
  - arm64-spot-nodepool.yaml
  - arm64-on-demand-nodepool.yaml
  # Node class
  - default-nodeclass.yaml
