tolerations:
  - effect: NoSchedule
    key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: linux

resources:
  requests:
    cpu: 126m
    memory: 100Mi
  limits:
    cpu: 126m
    memory: 106Mi
